classdef SolveMotionSmokeTest < matlab.unittest.TestCase
    % Smoke test for solve_motion: runs a short, cheap, bath-driven case at
    % the already-cached D5Quant20 domain (nr=50) and checks the output is
    % well-formed and physically sane. earlyStop is off so the test doesn't
    % depend on the rolling-mean-ratio convergence heuristic's timing.

    methods (Test)
        function runsAndReturnsFiniteBathDrivenCase(testCase)
            [t_s, CoM_cm, eta_history_cm] = solve_motion( ...
                'diskRadius', 0.2, 'diskMass', 0.0283, ...
                'forceAmplitude', 0.0, 'forceFrequency', 90, ...
                'bathAmplitude', 0.01, 'bathFrequency', 90, ...
                'phaseDifference', -90, ...
                'bathDensity', 1.175, 'bathSurfaceTension', 66.5, ...
                'bathViscosity', 0.18 / 1.175, ...
                'bathDiameter', 20, 'spatialResolution', 5, ...
                'temporalResolution', 30, 'simulationTime', 4 / 90, ...
                'debug_flag', false, 'solverType', 'lu', ...
                'startStatic', true, 'earlyStop', false);

            testCase.verifyEqual(numel(t_s), numel(CoM_cm));
            testCase.verifyTrue(all(isfinite(t_s)));
            testCase.verifyTrue(all(isfinite(CoM_cm)));
            testCase.verifyLessThan(max(abs(CoM_cm)), 10); % numerical-divergence guardrail in advance_one_step.m
            testCase.verifyGreaterThan(size(eta_history_cm, 1), 0);
        end
    end
end
